### ISSUE TITLE
update readme.md for more linux package installers (other than pacman)

### ISSUE THREAD

**Issue by ghost** [en-GB/3-manifold#3]
There's apt, there's yum, there's others, can you add them?

**Comment by ghost** [comment]
searched package name, only arch linux and compiling from source options appeared

**Comment by PyMaster22** [comment]
Hello @erenayar5 
I think I made a bash file that can install all requirements, compile, and run the program at the same time.
[runme.sh.zip](https://github.com/en-GB/3-manifold/files/4900709/runme.sh.zip)
If it doesn't work send me the error and I'll try to fix it.

**Comment by en-GB** [comment]
those were contributed by @MrYakobo if you make a pull request with a command that works for you ill accept it

**Comment by MrYakobo** [comment]
> There's apt, there's yum, there's others, can you add them?

@erenayar5  you're requiring quite a bit here from a package maintained by a single dude that appearently only uses Windows. A reasonable approach to install instructions for multiple operating systems is that people make pull requests when they find some sequences of commands that works on their machine.

If you yourself use centos, slackware, gentoo, macos or some other operating system not listed, go ahead and make a pull request. But don't expect @en-GB to research this in his free time instead of innovating on the main code base. The commands provided by @PyMaster22 is for `apt`-based distros.

**Comment by ghost** [comment]
i totally forgot about this issue existed but still thank you
